### ISSUE TITLE
A bug in  Time-Grad-Electricity.ipynb

### ISSUE THREAD

**Issue by UniqueRoHo** [zalandoresearch/pytorch-ts#113]
Exception: Caught Exception in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 28, in fetch
    data.append(next(self.dataset_iter))
  File "/usr/local/lib/python3.7/dist-packages/gluonts/transform/_base.py", line 104, in __iter__
    self.base_dataset, is_train=self.is_train
  File "/usr/local/lib/python3.7/dist-packages/gluonts/transform/_base.py", line 124, in __call__
    for data_entry in data_it:
  File "/usr/local/lib/python3.7/dist-packages/gluonts/transform/_base.py", line 124, in __call__
    for data_entry in data_it:
  File "/usr/local/lib/python3.7/dist-packages/gluonts/transform/_base.py", line 190, in __call__
    "Reached maximum number of idle transformation"
Exception: **Reached maximum number of idle transformation calls.
This means the transformation looped over 1 inputs without returning any output.
This occurred in the following transformation:**
gluonts.transform.split.InstanceSplitter(dummy_value=0.0, forecast_start_field="forecast_start", future_length=1, instance_sampler=gluonts.transform.sampler.ExpectedNumInstanceSampler(axis=-1, min_past=169, min_future=1, num_instances=1.0, total_length=130272, n=23), is_pad_field="is_pad", lead_time=0, output_NTC=True, past_length=169, start_field="start", target_field="target", time_series_fields=["time_feat", "observed_values"])

And my packages version as follow
torch  == 1.8.0
gluonts == 0.9.0

**Comment by ken-take-it-so-so** [comment]
Please try `pip install gluonts==0.10.0`

**Comment by UniqueRoHo** [comment]
Thanks a lot,  it worked！
