### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'freq'

### ISSUE THREAD

**Issue by hanlaoshi** [zalandoresearch/pytorch-ts#118]
Hi, When I reproduce the experiments, training is ok, but in forecasting, I got the exception. Some details are as follows.
(the version of packages: pytorchts-0.6.0, gluonts-0.10.0)

/home/axx/anaconda3/envs/torch2/lib/python3.8/site-packages/gluonts/dataset/multivariate_grouper.py:191: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return {FieldName.TARGET: np.array([funcs(data) for data in dataset])}
100%|███████████████████████████████████████████████████████| 99/99 [15:13<00:00,  9.23s/it, epoch=1/1, avg_loss=-64.6]
Traceback (most recent call last):
  File "Multivariate-Flow-Solar.py", line 202, in <module>
    predictor = estimator.train(dataset_train) #input_name:
  File "/home/axx/anaconda3/envs/torch2/lib/python3.8/site-packages/pts/model/estimator.py", line 179, in train
    return self.train_model(
  File "/home/aixx/anaconda3/envs/torch2/lib/python3.8/site-packages/pts/model/estimator.py", line 160, in train_model
    predictor=self.create_predictor(
  File "/home/axx/anaconda3/envs/torch2/lib/python3.8/site-packages/pts/model/tempflow/tempflow_estimator.py", line 244, in create_predictor
    return PyTorchPredictor(
TypeError: __init__() got an unexpected keyword argument 'freq'

When everyone faces the same problem, any assistance is greatly appreciated.

**Comment by kashif** [comment]
Can you kindly downgrade gluonts as I have not updated this lib. to use the new APIs etc.

**Comment by hanlaoshi** [comment]
> 

Thank you very much for your generous answers. Downgrading gluons from 0.10.0 to 0.9 works for me. By the way, if you downgrade your gluonts to 0.9, don't forget to change the file of ditribution_out.py in line 34(i.e. gluonts.torch.distributions.distribution_output-->gluonts.torch.modules.distribution_output)

**Comment by hanlaoshi** [comment]
Hi, @kashif, I sent you an email late last night, and I would appreciate it if you could find some time in your hectic work schedule to respond. Your study is really great, and I'll be basing my own scientific research on it!

**Comment by hanlaoshi** [comment]
> 

Hi, @kashif  Does the implementation of this code not use the multi-scale structure like the one in the Real-NVP paper?

**Comment by kashif** [comment]
@hanlaoshi not sure if i understand, but what do you mean by " multi-scale  structure" exactly? thanks!
