### ISSUE TITLE
Error while running the Multivariate-flow-solar example

### ISSUE THREAD

**Issue by AbhayGoyal** [zalandoresearch/pytorch-ts#121]
Hey,
I was trying to implement the example that has been mentioned and encountered the following error.

Exception: Reached maximum number of idle transformation calls.
This means the transformation looped over 1 inputs without returning any output.
This occurred in the following transformation:
gluonts.transform.split.InstanceSplitter(dummy_value=0.0, forecast_start_field="forecast_start", future_length=24, instance_sampler=gluonts.transform.sampler.ExpectedNumInstanceSampler(axis=-1, min_past=192, min_future=24, num_instances=1.0, total_length=54352, n=8), is_pad_field="is_pad", lead_time=0, output_NTC=True, past_length=192, start_field="start", target_field="target", time_series_fields=["time_feat", "observed_values"])

I do not understand the error is its complete sense. I do understand that there is some issue with gluonts but the method in which the data is setup is also a dictionary with the input data as a numpy ndarray. 

Could someone help me with this please?

**Comment by hughxx** [comment]
i found solution in other issue of this project, "https://github.com/zalandoresearch/pytorch-ts/issues/117
#117 opened on Oct 9 by [iliubenliang](https://github.com/zalandoresearch/pytorch-ts/issues?q=is%3Aissue+is%3Aopen+author%3Ailiubenliang)"

**Comment by hughxx** [comment]
i found solutoin in issue #117, that is "uninstall pytorchts", and  "pip install gluonts". And in my machine, i install gluonts without indicate the version(which in #117, it does), so you can try both.

**Comment by ken-take-it-so-so** [comment]
Hello.  
What is your gluonts version?

**Comment by AbhayGoyal** [comment]
It is 0.10.0

**Comment by AbhayGoyal** [comment]
even if I get the latest version i.e. the 0.11, the problem persists

**Comment by kashif** [comment]
so the above error is due to the fact that the instance sampler cannot for reason sample windows of context and subsequent prediction length size from the dataset such that there is a single sample in that window... usually this means that there is some issue with the dataset or the context or prediction length sizes... which dataset are you running this with?

**Comment by AbhayGoyal** [comment]
I am working with the 'solar nips' dataset

**Comment by kashif** [comment]
for which model? does this notebook work? https://github.com/zalandoresearch/pytorch-ts/blob/master/examples/Multivariate-Flow-Solar.ipynb

**Comment by AbhayGoyal** [comment]
I actually cloned the notebook and was running it when I encountered the following issue.


ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_1074892/3295418020.py in <module>
      1 from gluonts.dataset.multivariate_grouper import MultivariateGrouper
      2 from gluonts.dataset.repository.datasets import dataset_recipes, get_dataset
----> 3 from pts.model.tempflow import TempFlowEstimator
      4 from pts.model.transformer_tempflow import TransformerTempFlowEstimator
      5 from pts import Trainer

/usr/local/lib/python3.8/dist-packages/pts/model/tempflow/__init__.py in <module>
----> 1 from .tempflow_estimator import TempFlowEstimator
      2 from .tempflow_network import TempFlowTrainingNetwork, TempFlowPredictionNetwork

/usr/local/lib/python3.8/dist-packages/pts/model/tempflow/tempflow_estimator.py in <module>
     35 from pts.model import PyTorchEstimator
     36 
---> 37 from .tempflow_network import TempFlowTrainingNetwork, TempFlowPredictionNetwork
     38 
     39 

/usr/local/lib/python3.8/dist-packages/pts/model/tempflow/tempflow_network.py in <module>
      7 
      8 from pts.model import weighted_average
----> 9 from pts.modules import RealNVP, MAF, FlowOutput, MeanScaler, NOPScaler
     10 
     11 

/usr/local/lib/python3.8/dist-packages/pts/modules/__init__.py in <module>
----> 1 from .distribution_output import (
      2     NormalOutput,
      3     StudentTOutput,
      4     BetaOutput,
      5     PoissonOutput,

/usr/local/lib/python3.8/dist-packages/pts/modules/distribution_output.py in <module>
     32 )
     33 from gluonts.core.component import validated
---> 34 from gluonts.torch.modules.distribution_output import (
     35     DistributionOutput,
     36     LambdaLayer,

ModuleNotFoundError: No module named 'gluonts.torch.modules.distribution_output'

**Comment by kashif** [comment]
right that is as i mentioned because the new gluonts has changed its API so you can try to run it with an older version of gluonts or i need to update the API on my side here...

**Comment by AbhayGoyal** [comment]
Yup. I saw that this change happened with 0.7 version of gluonts. But even I go to 0.6.x version, I get this issue

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_1074892/3295418020.py in <module>
      1 from gluonts.dataset.multivariate_grouper import MultivariateGrouper
      2 from gluonts.dataset.repository.datasets import dataset_recipes, get_dataset
----> 3 from pts.model.tempflow import TempFlowEstimator
      4 from pts.model.transformer_tempflow import TransformerTempFlowEstimator
      5 from pts import Trainer

/usr/local/lib/python3.8/dist-packages/pts/model/tempflow/__init__.py in <module>
----> 1 from .tempflow_estimator import TempFlowEstimator
      2 from .tempflow_network import TempFlowTrainingNetwork, TempFlowPredictionNetwork

/usr/local/lib/python3.8/dist-packages/pts/model/tempflow/tempflow_estimator.py in <module>
     35 from pts.model import PyTorchEstimator
     36 
---> 37 from .tempflow_network import TempFlowTrainingNetwork, TempFlowPredictionNetwork
     38 
     39 

/usr/local/lib/python3.8/dist-packages/pts/model/tempflow/tempflow_network.py in <module>
      7 
      8 from pts.model import weighted_average
----> 9 from pts.modules import RealNVP, MAF, FlowOutput, MeanScaler, NOPScaler
     10 
     11 

/usr/local/lib/python3.8/dist-packages/pts/modules/__init__.py in <module>
----> 1 from .distribution_output import (
      2     NormalOutput,
      3     StudentTOutput,
      4     BetaOutput,
      5     PoissonOutput,

/usr/local/lib/python3.8/dist-packages/pts/modules/distribution_output.py in <module>
     32 )
     33 from gluonts.core.component import validated
---> 34 from gluonts.torch.modules.distribution_output import (
     35     DistributionOutput,
     36     LambdaLayer,

~/.local/lib/python3.8/site-packages/gluonts/torch/modules/distribution_output.py in <module>
     28 
     29 # First-party imports
---> 30 from gluonts.core.component import DType, validated
     31 
     32 # Relative imports

ImportError: cannot import name 'DType' from 'gluonts.core.component' (/usr/local/home/aghnw/.local/lib/python3.8/site-packages/gluonts/core/component.py)

**Comment by kashif** [comment]
hmm ok let me fix it so that this works with the latest gluonts then...

**Comment by AbhayGoyal** [comment]
thanks

**Comment by wassname** [comment]
I have the same error on multiple notebooks. I find glounts data transforms to be quite hard to debug and inspect. But here's a hack that worked for me:


change `with env._let(max_idle_transforms=maybe_len(training_data) or 0):`
to `with env._let(max_idle_transforms=10):` 
in estimator.py.

It works. I guess the splitter skips a few invalid windows but then find some valid ones.

**Comment by liu-dian** [comment]
> Yup. I saw that this change happened with 0.7 version of gluonts. But even I go to 0.6.x version, I get this issue
> 
> ImportError Traceback (most recent call last) /tmp/ipykernel_1074892/3295418020.py in 1 from gluonts.dataset.multivariate_grouper import MultivariateGrouper 2 from gluonts.dataset.repository.datasets import dataset_recipes, get_dataset ----> 3 from pts.model.tempflow import TempFlowEstimator 4 from pts.model.transformer_tempflow import TransformerTempFlowEstimator 5 from pts import Trainer
> 
> /usr/local/lib/python3.8/dist-packages/pts/model/tempflow/**init**.py in ----> 1 from .tempflow_estimator import TempFlowEstimator 2 from .tempflow_network import TempFlowTrainingNetwork, TempFlowPredictionNetwork
> 
> /usr/local/lib/python3.8/dist-packages/pts/model/tempflow/tempflow_estimator.py in 35 from pts.model import PyTorchEstimator 36 ---> 37 from .tempflow_network import TempFlowTrainingNetwork, TempFlowPredictionNetwork 38 39
> 
> /usr/local/lib/python3.8/dist-packages/pts/model/tempflow/tempflow_network.py in 7 8 from pts.model import weighted_average ----> 9 from pts.modules import RealNVP, MAF, FlowOutput, MeanScaler, NOPScaler 10 11
> 
> /usr/local/lib/python3.8/dist-packages/pts/modules/**init**.py in ----> 1 from .distribution_output import ( 2 NormalOutput, 3 StudentTOutput, 4 BetaOutput, 5 PoissonOutput,
> 
> /usr/local/lib/python3.8/dist-packages/pts/modules/distribution_output.py in 32 ) 33 from gluonts.core.component import validated ---> 34 from gluonts.torch.modules.distribution_output import ( 35 DistributionOutput, 36 LambdaLayer,
> 
> ~/.local/lib/python3.8/site-packages/gluonts/torch/modules/distribution_output.py in 28 29 # First-party imports ---> 30 from gluonts.core.component import DType, validated 31 32 # Relative imports
> 
> ImportError: cannot import name 'DType' from 'gluonts.core.component' (/usr/local/home/aghnw/.local/lib/python3.8/site-packages/gluonts/core/component.py)

when I installed the gluonts==0.9.0 ,the problem was tackled.

**Comment by AbhayGoyal** [comment]
Ah ok. I am also facing this issue with the code. Is it possible that this is also because of the gluonts version?

Traceback (most recent call last):
  File "C:\Users\goyal\Downloads\grace-pnnl-main_updated\grace-pnnl-main\Probabilistic Forecasting\multiflow.py", line 27, in <module>
    dataset_test = test_grouper(dataset.test)
  File "C:\Users\goyal\PycharmProjects\pythonProject\venv\lib\site-packages\gluonts\dataset\multivariate_grouper.py", line 91, in __call__
    return self._group_all(dataset)
  File "C:\Users\goyal\PycharmProjects\pythonProject\venv\lib\site-packages\gluonts\dataset\multivariate_grouper.py", line 118, in _group_all
    grouped_dataset = self._prepare_test_data(dataset)
  File "C:\Users\goyal\PycharmProjects\pythonProject\venv\lib\site-packages\gluonts\dataset\multivariate_grouper.py", line 138, in _prepare_test_data
    grouped_data = self._transform_target(self._left_pad_data, dataset)
  File "C:\Users\goyal\PycharmProjects\pythonProject\venv\lib\site-packages\gluonts\dataset\multivariate_grouper.py", line 184, in _transform_target
    return {FieldName.TARGET: np.array([funcs(data) for data in dataset])}
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (959,) + inhomogeneous part.

**Comment by kevindarby** [comment]
> ModuleNotFoundError: No module named 'gluonts.torch.modules.distribution_output'

Hi all, just a heads up that if you replace modules.distribution_output with distribution.distribution_output this gets better.

also, 

change 

        with env._let(max_idle_transforms=maybe_len(training_data) or 0):
to 
        with env._let(max_idle_transforms=100):

in estimator.py and most of the solar notebook starts to work
