### ISSUE TITLE
File not found: datasets/pts_m5/metadata.json

### ISSUE THREAD

**Issue by cowwoc** [zalandoresearch/pytorch-ts#65]
Excuse me if this is a newbie question but when I try to run https://github.com/zalandoresearch/pytorch-ts/blob/master/examples/m5-tft.ipynb I am running into the following error:

```
Traceback (most recent call last):
  File "C:\Users\Gili\Documents\myproject\pytorch-ts-test.py", line 17, in <module>
    dataset = get_dataset("pts_m5", regenerate=False)
  File "C:\Users\Gili\Documents\myproject\python\lib\site-packages\gluonts\dataset\repository\datasets.py", line 232, in get_dataset
    return load_datasets(
  File "C:\Users\Gili\Documents\myproject\python\lib\site-packages\gluonts\dataset\common.py", line 491, in load_datasets
    meta = MetaData.parse_file(Path(metadata) / "metadata.json")
  File "pydantic\main.py", line 613, in pydantic.main.BaseModel.parse_file
  File "pydantic\parse.py", line 57, in pydantic.parse.load_file
  File "C:\Python39\lib\pathlib.py", line 1248, in read_bytes
    with self.open(mode='rb') as f:
  File "C:\Python39\lib\pathlib.py", line 1241, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "C:\Python39\lib\pathlib.py", line 1109, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Gili\\.mxnet\\gluon-ts\\datasets\\pts_m5\\metadata.json'
```

Looking at https://www.kaggle.com/c/m5-forecasting-accuracy/data this file does not seem to exist. What am I missing here?

**Comment by slaweks17** [comment]
I have the same problem

**Comment by kashif** [comment]
So once the appropriate files from kaggle are in the folder then you need to:

```py
 get_dataset("pts_m5", regenerate=True)
```

to generate the files which can be used by the gluonts/pytorchts models

**Comment by slaweks17** [comment]
Thank you. And, I would add, be patient, it takes at least half an hour.

**Comment by kashif** [comment]
@slaweks17 yes I might be doing something dumb... I would appreciate another pair of eyes to look through that code in https://github.com/zalandoresearch/pytorch-ts/blob/master/pts/dataset/repository/_m5.py

**Comment by slaweks17** [comment]
OK, I will try.

**Comment by kashif** [comment]
oh @slaweks17 ! I didn't realise it is you Slawek. Let me know if you have any other questions etc. I am busy this next week with ICML but I will try to make some time perhaps in 2 weeks?

**Comment by slaweks17** [comment]
Sure! I will also learn more about your project before then.

Have a nice weekend,
Slawek


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by cowwoc** [comment]
Is it possible to add this step to the README?
